# Generated by Django 3.0.3 on 2020-03-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20200303_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
