# Generated by Django 3.0.3 on 2020-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20200303_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
