# Generated by Django 2.2.2 on 2020-03-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20200303_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(),
        ),
    ]
