# Generated by Django 2.2.2 on 2020-03-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20200304_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
