# Generated by Django 3.0.3 on 2020-02-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
