# Generated by Django 3.0.3 on 2020-02-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_owner_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
