# Generated by Django 3.0.3 on 2020-03-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('pet', '0003_auto_20200229_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='services',
            field=models.ManyToManyField(to='service.Service'),
        ),
    ]
