# Generated by Django 3.0.3 on 2020-03-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('pet', '0006_auto_20200303_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='rooms',
        ),
        migrations.AddField(
            model_name='pet',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.Room'),
        ),
    ]
