# Generated by Django 3.0.3 on 2020-03-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('pet', '0007_auto_20200303_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='services',
            field=models.ManyToManyField(blank=True, to='service.Service'),
        ),
    ]
