# Generated by Django 2.2.2 on 2020-03-07 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_auto_20200303_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.Room'),
        ),
    ]
