# Generated by Django 2.2.2 on 2020-03-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_auto_20200307_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
    ]
