# Generated by Django 2.2.2 on 2020-03-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_auto_20200307_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='services',
        ),
    ]
