# Generated by Django 2.2.2 on 2020-03-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200307_2142'),
        ('pet', '0011_remove_pet_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='services',
            field=models.ManyToManyField(blank=True, to='service.Service'),
        ),
    ]
