# Generated by Django 2.2.2 on 2020-03-08 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_pet_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='room',
        ),
    ]
