# Generated by Django 2.2.2 on 2020-03-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200304_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
